namespace Klf.Application.Interfaces.Storage;

/// <summary>Stores uploaded files (Cloudflare R2 in production, a local folder in development).</summary>
public interface IFileStorage
{
    /// <summary>Saves a file under the given key, replacing any file with the same key.</summary>
    /// <param name="key">Storage key, generated by the server.</param>
    /// <param name="content">File content.</param>
    /// <param name="contentType">Type served to browsers (e.g. <c>image/png</c>).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task SaveAsync(string key, Stream content, string contentType, CancellationToken cancellationToken);

    /// <summary>Deletes a file. Deleting a file that does not exist is not an error.</summary>
    /// <param name="key">Storage key.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task DeleteAsync(string key, CancellationToken cancellationToken);

    /// <summary>Returns the public address a browser can use to load the file.</summary>
    /// <param name="key">Storage key.</param>
    string GetPublicUrl(string key);
}
