using Klf.Domain.Common;

namespace Klf.Domain.Entities;

/// <summary>
/// An uploaded image. The file itself lives in the file storage; this row keeps its metadata
/// and is what covers, logos, photos and album items point to.
/// </summary>
public sealed class MediaAsset : SoftDeletableEntity
{
    /// <summary>Creates the metadata of an uploaded image.</summary>
    /// <param name="storageKey">Key of the file in the storage (generated by the server, never from the user).</param>
    /// <param name="originalFileName">File name the user uploaded, only to recognize the image in the panel.</param>
    /// <param name="contentType">Detected image type (e.g. <c>image/png</c>).</param>
    /// <param name="sizeBytes">File size in bytes.</param>
    /// <param name="altText">Text alternative for screen readers; optional.</param>
    public MediaAsset(string storageKey, string originalFileName, string contentType, long sizeBytes, string? altText)
    {
        StorageKey = storageKey;
        OriginalFileName = originalFileName;
        ContentType = contentType;
        SizeBytes = sizeBytes;
        AltText = altText;
    }

    /// <summary>Key of the file in the storage.</summary>
    public string StorageKey { get; private set; }

    /// <summary>File name the user uploaded.</summary>
    public string OriginalFileName { get; private set; }

    /// <summary>Detected image type (e.g. <c>image/png</c>).</summary>
    public string ContentType { get; private set; }

    /// <summary>File size in bytes.</summary>
    public long SizeBytes { get; private set; }

    /// <summary>Text alternative for screen readers; optional.</summary>
    public string? AltText { get; private set; }

    /// <summary>Replaces the text alternative.</summary>
    /// <param name="altText">New text alternative; <see langword="null"/> clears it.</param>
    public void UpdateAltText(string? altText) => AltText = altText;
}
